# Generated by Django 5.2.1 on 2025-07-16 18:15

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expiry_date',
            field=models.DateTimeField(default=main.models.Property.default_expiry),
        ),
    ]
