# Generated by Django 5.2.1 on 2025-07-24 06:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeuser',
            name='email_confirmation_token',
            field=models.UUIDField(null=True, editable=False, ),
        ),
        migrations.AddField(
            model_name='completeuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
