# Generated by Django 5.2.1 on 2025-07-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_property_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='detailed_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
