# Generated by Django 5.2.1 on 2025-05-25 11:58

import main.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_propertyimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='images',
            field=models.ImageField(storage=main.storages.MediaStorage(), upload_to='restate_ads/'),
        ),
    ]
