# Generated by Django 5.2.1 on 2025-07-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_property_detailed_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpayment',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
