# Generated by Django 5.2.1 on 2025-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_propertyimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('single room', 'single room'), ('self contained', 'self contained'), ('chamber & hall', 'chamber & hall'), ('apartment', 'apartment'), ('serviced apartment', 'serviced apartment'), ('duplex', 'duplex'), ('hostel', 'hostel'), ('guest house', 'guest house'), ('commercial', 'commercial')], default='apartment', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('not available', 'not availble')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('rental', 'rental'), ('short rental', 'short-rental'), ('sale', 'sale')], default='rental', max_length=50),
        ),
    ]
