# Generated by Django 5.2.1 on 2025-07-24 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250724_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeuser',
            name='email_confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
