# Generated by Django 5.2.1 on 2025-07-24 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_completeuser_email_confirmation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeuser',
            name='token_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
