# Generated by Django 5.2.1 on 2025-05-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_property_property_type_alter_property_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('rental', 'rental'), ('short rental', 'short rental'), ('sale', 'sale')], default='rental', max_length=50),
        ),
    ]
