# Generated by Django 5.2.1 on 2025-07-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_completeuser_token_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeuser',
            name='email_confirmation_token',
        ),
        migrations.RemoveField(
            model_name='completeuser',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='completeuser',
            name='token_created_at',
        ),
    ]
