# Generated by Django 5.2.1 on 2025-07-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_propertyimage_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('needs_renovation', 'Needs Renovation')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='secure_parking',
            field=models.BooleanField(default=False, help_text='Gated or guarded parking'),
        ),
        migrations.AddField(
            model_name='property',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this property has been viewed'),
        ),
        migrations.AddField(
            model_name='property',
            name='wheelchair_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
